export const data = {
  1: {
    team: [],
    performances: [],
  },
  2: {
    team: [
      {
        id: 1,
        name: "Abhisaradev Murmu",
        role: "dancer",
        email: "email@email.com",
        insta: "instauser",
      },
      {
        id: 2,
        name: "Adithya Harihara",
        role: "captain",
        email: "email@email.com",
        insta: "instauser",
      },
      {
        id: 3,
        name: "Afzal Jakir",
        role: "dancer",
        email: "email@email.com",
        insta: "instauser",
      },
      {
        id: 4,
        name: "Akash Shah",
        role: "dancer",
        email: "email@email.com",
        insta: "instauser",
      },
      {
        id: 5,
        name: "Amit Yeleswarapu",
        role: "dancer",
        email: "email@email.com",
        insta: "instauser",
      },
      {
        id: 6,
        name: "Anubhav Kamath",
        role: "dancer",
        email: "email@email.com",
        insta: "instauser",
      },
      {
        id: 7,
        name: "Arham Kothari",
        role: "dancer",
        email: "email@email.com",
        insta: "instauser",
      },
      {
        id: 8,
        name: "Arnav Karandikar",
        role: "dancer",
        email: "email@email.com",
        insta: "instauser",
      },
      {
        id: 9,
        name: "Athulya Rajakumar",
        role: "manager",
        email: "email@email.com",
        insta: "instauser",
      },
      {
        id: 10,
        name: "Ayush Singh",
        role: "dancer",
        email: "email@email.com",
        insta: "instauser",
      },
      {
        id: 11,
        name: "Chinmay Pingale",
        role: "dancer",
        email: "email@email.com",
        insta: "instauser",
      },
      {
        id: 12,
        name: "Kabir Bhakta",
        role: "dancer",
        email: "email@email.com",
        insta: "instauser",
      },
      {
        id: 13,
        name: "Manas Agarwal",
        role: "social",
        email: "email@email.com",
        insta: "instauser",
      },
      {
        id: 14,
        name: "Manish Bhandari",
        role: "dancer",
        email: "email@email.com",
        insta: "instauser",
      },
      {
        id: 15,
        name: "Nikhil Erabelli",
        role: "dancer",
        email: "email@email.com",
        insta: "instauser",
      },
      {
        id: 16,
        name: "Rohan Singeetham",
        role: "production",
        email: "email@email.com",
        insta: "instauser",
      },
      {
        id: 17,
        name: "Sanchith Shanmuga",
        role: "dancer",
        email: "email@email.com",
        insta: "instauser",
      },
      {
        id: 18,
        name: "Shikhar Gupta",
        role: "dancer",
        email: "email@email.com",
        insta: "instauser",
      },
      {
        id: 19,
        name: "Sid Singh",
        role: "production",
        email: "email@email.com",
        insta: "instauser",
      },
      {
        id: 20,
        name: "Sunhith Mundla",
        role: "dancer",
        email: "email@email.com",
        insta: "instauser",
      },
      {
        id: 21,
        name: "Swayam Barik",
        role: "captain",
        email: "email@email.com",
        insta: "instauser",
      },
      {
        id: 22,
        name: "Twinkle Khanna",
        role: "choreo",
        email: "email@email.com",
        insta: "instauser",
      },
      {
        id: 23,
        name: "Vansh Jain",
        role: "finance",
        email: "email@email.com",
        insta: "instauser",
      },
      {
        id: 24,
        name: "Vasu Mahapatra",
        role: "graphics",
        email: "email@email.com",
        insta: "instauser",
      },
      {
        id: 25,
        name: "Vyshnav Nair",
        role: "dancer",
        email: "email@email.com",
        insta: "instauser",
      },
      {
        id: 26,
        name: "Yash Aggarwal",
        role: "dancer",
        email: "email@email.com",
        insta: "instauser",
      },
    ],
    sliderTotal: 4,
    performances: [
      "https://www.youtube.com/watch?v=vr5QwTXh5t8",
      "https://www.youtube.com/watch?v=OPRumImYUPU",
      "https://www.youtube.com/watch?v=8ztoXsv9hKc",
    ],
  },
  3: {
    team: [
      {
        id: 1,
        name: "Aayush Singh",
        role: "dancer",
        email: "aayushsingh0318@gmail.com",
        insta: "instauser",
      },
      {
        id: 2,
        name: "Abhisaradev Murmu",
        role: "captain",
        email: "abhisaradev@gmail.com",
        insta: "instauser",
      },
      {
        id: 3,
        name: "Abhijit Harihara",
        role: "dancer",
        email: "abhiharihara@gmail.com",
        insta: "instauser",
      },
      {
        id: 4,
        name: "Adithya Harihara",
        role: "captain",
        email: "adithyaharihara@gmail.com",
        insta: "instauser",
      },
      {
        id: 5,
        name: "Akash Shah",
        role: "dancer",
        email: "",
        insta: "",
      },
      {
        id: 5,
        name: "Amitesh Yeleswarapu",
        role: "board",
        email: "",
        insta: "",
      },
      {
        id: 5,
        name: "I'm Vengeance",
        role: "dancer",
        email: "",
        insta: "",
      },
      // {
      //   id: 5,
      //   name: "Anand Iyer",
      //   role: "dancer",
      //   email: "",
      //   insta: "",
      // },
      {
        id: 5,
        name: "Anubhav Kamath",
        role: "dancer",
        email: "",
        insta: "",
      },
      {
        id: 5,
        name: "Arham Kothari",
        role: "dancer",
        email: "",
        insta: "",
      },
      {
        id: 5,
        name: "Arnav Karandikar",
        role: "Social",
        email: "",
        insta: "",
      },
      {
        id: 5,
        name: "Ashwin Desai",
        role: "dancer",
        email: "",
        insta: "",
      },
      {
        id: 5,
        name: "Kabir Bhakta",
        role: "DJ",
        email: "",
        insta: "",
      },
      {
        id: 5,
        name: "Mahek Bhargava",
        role: "Manager",
        email: "",
        insta: "",
      },
      {
        id: 5,
        name: "Manas Agarwal",
        role: "dancer",
        email: "",
        insta: "",
      },
      {
        id: 5,
        name: "Manish Bhandari",
        role: "Tech",
        email: "",
        insta: "",
      },
      {
        id: 5,
        name: "Mithila Harirama",
        role: "Manager",
        email: "",
        insta: "",
      },
      {
        id: 5,
        name: "Nick Otwani",
        role: "dancer",
        email: "",
        insta: "",
      },
      {
        id: 5,
        name: "Nikhil Erabelli",
        role: "Logistics",
        email: "",
        insta: "",
      },
      {
        id: 5,
        name: "Rohan Singeetham",
        role: "Production",
        email: "",
        insta: "",
      },
      {
        id: 5,
        name: "Rohit Shetty",
        role: "dancer",
        email: "",
        insta: "",
      },
      {
        id: 5,
        name: "Sanchith Shanmuga",
        role: "Social",
        email: "",
        insta: "",
      },
      {
        id: 5,
        name: "Sathya Balakumar",
        role: "dancer",
        email: "",
        insta: "",
      },
      {
        id: 5,
        name: "Shikhar Gupta",
        role: "Production",
        email: "",
        insta: "",
      },
      {
        id: 5,
        name: "Siddarth Rayapur",
        role: "dancer",
        email: "",
        insta: "",
      },
      {
        id: 5,
        name: "Simki Palicha",
        role: "Choreographer",
        email: "",
        insta: "",
      },
      {
        id: 5,
        name: "Sunhith Mundla",
        role: "Social",
        email: "",
        insta: "",
      },
      {
        id: 5,
        name: "Tejas Bansal",
        role: "dancer",
        email: "",
        insta: "",
      },
      {
        id: 5,
        name: "Twinkle Khanna",
        role: "Choreographer",
        email: "",
        insta: "",
      },
      {
        id: 5,
        name: "Vansh Jain",
        role: "Finance",
        email: "",
        insta: "",
      },
      {
        id: 5,
        name: "Vyshnav Nair",
        role: "dancer",
        email: "",
        insta: "",
      },
      {
        id: 5,
        name: "Yash Aggarwal",
        role: "dancer",
        email: "",
        insta: "",
      },
      {
        id: 5,
        name: "Yash Agarwal",
        role: "dancer",
        email: "",
        insta: "",
      },
    ],
    sliderTotal: 5,
    performances: [
      "https://www.youtube.com/watch?v=pio6rOe31ag",
      "https://www.youtube.com/watch?v=cML5p3-Lotc",
      "https://www.youtube.com/watch?v=NrIFmcSifHM",
      "https://www.youtube.com/watch?v=LCnV47xrN4I",
    ],
  },
};
